server:
  port: 10000

spring:
  logging:
    level:
      org.springframework.security: INFO
  profiles:
    active: DEV
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    database: 0
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/autopush?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      # 是否允许暂停连接池，暂停后getConnection方法都会被阻塞，用于模拟连接故障，生产环境使用默认配置false
      allow-pool-suspension: false
      #      空闲连接数
      minimum-idle: 5
      #      最大连接数
      maximum-pool-size: 50
      connection-test-query: select 1
      #      一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 100000
      #      一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 120000
      connection-timeout: 30000
      connection-init-sql: set names utf8mb4
      pool-name: DatebookHikariCP
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  #MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:mapper/*.xml
  #  MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，
  #注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  typeAliasesPackage: com.jason.models
  # 与 typeAliasesPackage 一起使用，仅扫描以该类作为父类的类
  # type-aliases-super-type: java.lang.Object
  # 配置扫描通用枚举,配置该属性，会对枚举类进行注入
  typeEnumsPackage: com.jason.autopush.en
  # 该包下的类注册为自定义类型转换处理类，用于属性类型转换
  # type-handlers-package: com.luwei.demo.mybatisplusdemo.handler
  # 指定 mybatis 处理器
  # executorType: simple

  configuration:
    #使用驼峰法映射属性,配置这个resultType可以映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 配置表明前缀，例如表设计时表名为tb_manager，对应entity为Manager
      table-prefix: tb_
      #逻辑已删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0
      # 是否开启like查询，即对 stirng 字段是否使用 like，默认不开启
      # column-like: false

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:10002/auth/current