jason:
  server:
    port: 8081
    host: localhost

spring:
  logging:
    level:
      org.springframework.security: INFO
  profiles:
    active: DEV
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    database: 0
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/autopush?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      # 是否允许暂停连接池，暂停后getConnection方法都会被阻塞，用于模拟连接故障，生产环境使用默认配置false
      allow-pool-suspension: false
      #      空闲连接数
      minimum-idle: 5
      #      最大连接数
      maximum-pool-size: 50
      connection-test-query: select 1
      #      一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 100000
      #      一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 120000
      connection-timeout: 30000
      connection-init-sql: set names utf8mb4
      pool-name: DatebookHikariCP
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-parser-cache: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:10002/auth/current

